---
title: "R-projects"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{R-projects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



# How to create an R project

In RStudio, use File -> New Project

## Recommended libraries

```
library(usethis)
library(devtools)
library(testthat)
library(roxygen2)
```

## Unit testing

To add a 'tests' folder

```
library(devtools)
install.packages("testthat")
install.packages("usethis")
usethis::use_testthat()
```

Do `use_testthat()` only once.

To add a unit test function

```
use_test("hello_test")
```

and then edit the newly-created R file to implement the desired unit tests.

## To add a vignette

```
usethis::use_vignette("R-projects")
```

## To add the package to GitHub

Change into the package directory, and then

```
git init
# Adjust the .gitignore file appropriately before doing the next command.
git add .
git commit -a
```

Then make an empty repository on GitHub, and then

```
git remote add origin https://github.com/UserName/RepositoryName
git push -u origin master
```

I added the `.Rproj.user` folder and the `dweeks.Rproj` file to the repository by mistake. 
To remove them from the repository while retaining the local copies, do the following:

```
git rm --cached -r .Rproj.user
git rm --cached dweeks.Rproj
git commit -m "Removing .Rproj.user and dweeks.Rproj"
git push
```

And adjust the `.gitignore` file appropriately.

## Adding Travis CI support 

Create a .travis.yml in the root directory of the package that contains these lines:

```
language: r
sudo: false
cache: packages

warnings_are_errors: true
```

And adjust the `.Rbuildignore` file to ignore the `.travis.yml` file.

## Adding Travis CI support for lintr

### Approach 1: via the .travis.yml file:

Add these lines to the end of the .travis.yml file:

```

r_packages:
  - lintr

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
```

### Approach 2: via a testthat function

```
if (requireNamespace("lintr", quietly = TRUE)) {
  context("lints")
  test_that("Package Style", {
    lintr::expect_lint_free()
  })
}
```

and add this to the DESCRIPTION file:

```
Suggests: lintr
```

## Manually checking your package with lintr

```
library(lintr)
lint_package()
```
